name: Build and Test

on:
  push:
    branches:
      - main
      - master

jobs:
  unit-coverage:
    name: Unit coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.302
    - run: dotnet run --project build/build.csproj

    - name: Assert slice coverage is not empty
      run: python3 tests/assert-cobertura-not-empty.py 'artifacts/coverage/slice/**/coverage.cobertura.xml'

    - name: Upload slice coverage
      if: success()
      uses: actions/upload-artifact@v7
      with:
        name: slice-cobertura
        path: artifacts/coverage/slice/**/coverage.cobertura.xml
        if-no-files-found: error
        retention-days: 14
